server:
  port: 8001

spring:
  application:
    name: CLOUD-PAYMENT-SERVICE
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: 15320721xzw12340
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1  #采样率介于0-1之间，1表示全部采集

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xtl.entity

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9001/eureka,http://localhost:9002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true  #访问路径可以显示IP地址
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20