server:
  port: 8011

spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.188.130:1314

management:
  endpoints:
    web:
      exposure:
        include: "*"